### ISSUE TITLE
New role, new permissions

### ISSUE THREAD

**Issue by fungl164** [qor/roles#2]
Hi,

Given that new role instances can be created, should `role.newPermissions()` be made public?

This would much less cumbersome and less error-prone than constructing a new `Permission` manually or calling `roles.NewPermission()` and ensuring the appropriate role instance is captured....

Many Thnxs!

**Comment by jinzhu** [comment]
I think it is not necessary to  constructing a new `Permission` manually? just use `Allow`, `Deny`?
