### ISSUE TITLE
Removing roles

### ISSUE THREAD

**Issue by fungl164** [qor/roles#3]
Hi,

Right now it is not possible to remove or reset role definitions.  It would be awesome to have the following utility functions if possible:

``` go
// Remove role definitions
func (role *Role) Remove(name string) {
    delete(role.definitions, name)
}

// Reset role definitions
func (role *Role) Reset() {
    role.definitions = map[string]func(req *http.Request, currentUser interface{}) bool{}
}
```

Msny Thnxs!

**Comment by jinzhu** [comment]
I think it is not necessary to remove a defined name, you could just create another roles set.
